import type { IApiGuide, IGuideLocale } from './api-guides.js'

type IUtilsGuideInput = {
  readonly purposeEn: string
  readonly purposeZh: string
  readonly quickStart: string
  readonly useEn: string
  readonly useZh: string
  readonly avoidEn: string
  readonly avoidZh: string
}

/** Builds one explicit bilingual Utils API decision guide. */
function utilsGuide(input: IUtilsGuideInput): Readonly<Record<IGuideLocale, IApiGuide>> {
  return {
    en: {
      purpose: input.purposeEn,
      quickStart: input.quickStart,
      scenarios: [input.useEn, 'The behavior must stay identical across all consumers that share this utility contract.'],
      avoidWhen: [input.avoidEn, 'A domain owner already exposes a narrower operation with the required lifecycle or error policy.'],
      options: []
    },
    zh: {
      purpose: input.purposeZh,
      quickStart: input.quickStart,
      scenarios: [input.useZh, '所有共享该 utility contract 的 consumer 必须获得一致行为。'],
      avoidWhen: [input.avoidZh, 'domain owner 已经公开包含所需 lifecycle 或 error policy 的更窄 operation。'],
      options: []
    }
  }
}

/** Human-maintained guides for byte, configuration, error, and callable utilities. */
const foundationalUtilsApiGuides: Readonly<
  Record<string, Readonly<Record<IGuideLocale, IApiGuide>>>
> = {
  'utils:index:collect': utilsGuide({
    purposeEn:
      'Creates a lazy, ordered, single-pass query pipeline over a borrowed readonly array and caches one result snapshot per query revision.',
    purposeZh:
      '基于借用的 readonly array 创建惰性、有序、单次扫描的查询流水线，并为每个 query revision 缓存一次结果快照。',
    quickStart:
      "const visible = collect(users).fieldBy('profile.name').like(search).where(user => user.active).take(20).result",
    useEn:
      'An in-memory list needs composable field filtering, predicates, stable deduplication, or pagination without allocating an intermediate array for every stage.',
    useZh:
      '内存列表需要组合字段筛选、predicate、稳定去重或分页，同时避免每个阶段都分配中间数组。',
    avoidEn:
      'The data is remote, mutates behind the collector, needs reactive invalidation, or requires indexed lookup and database query planning.',
    avoidZh:
      '数据来自远端、会在 collector 背后修改、需要响应式失效，或需要索引查询与数据库 query plan。'
  }),
  'utils:bytes:encodeUtf8': utilsGuide({ purposeEn: 'Encodes a JavaScript string as UTF-8 bytes with the host TextEncoder contract.', purposeZh: '按宿主 TextEncoder contract 把 JavaScript string 编码为 UTF-8 bytes。', quickStart: "import { encodeUtf8 } from '@migaia/utils'\n\nconst bytes = encodeUtf8('Migaia')", useEn: 'Text must cross a binary storage, hashing, or transport boundary.', useZh: 'text 需要跨 binary storage、hashing 或 transport boundary。', avoidEn: 'The destination expects UTF-16 code units or another character encoding.', avoidZh: 'destination 期望 UTF-16 code unit 或其他 character encoding。' }),
  'utils:bytes:decodeUtf8': utilsGuide({ purposeEn: 'Decodes UTF-8 bytes into a JavaScript string using one consistent TextDecoder boundary.', purposeZh: '通过统一 TextDecoder boundary 把 UTF-8 bytes 解码为 JavaScript string。', quickStart: "import { decodeUtf8, encodeUtf8 } from '@migaia/utils'\n\nconst bytes = encodeUtf8('Migaia')\nconst text = decodeUtf8(bytes)\nconsole.log(text) // Migaia", useEn: 'UTF-8 data returns from storage, a stream, or a transport.', useZh: 'UTF-8 data 从 storage、stream 或 transport 返回。', avoidEn: 'The byte sequence uses a different encoding or invalid input must be rejected with a custom fatal policy.', avoidZh: 'byte sequence 使用其他 encoding，或 invalid input 需要 custom fatal policy。' }),
  'utils:bytes:utf8ByteLength': utilsGuide({ purposeEn: 'Returns the encoded UTF-8 byte count rather than JavaScript UTF-16 string length.', purposeZh: '返回 UTF-8 encoded byte count，而不是 JavaScript UTF-16 string length。', quickStart: "import { utf8ByteLength } from '@migaia/utils'\n\nconst size = utf8ByteLength('你好') // 6", useEn: 'A transport, storage, or chunk budget is measured in wire bytes.', useZh: 'transport、storage 或 chunk budget 按 wire byte 计算。', avoidEn: 'The caller needs character, grapheme, or UTF-16 code-unit length.', avoidZh: 'caller 需要 character、grapheme 或 UTF-16 code-unit length。' }),
  'utils:bytes:splitUtf8': utilsGuide({ purposeEn: 'Splits text into ordered chunks whose UTF-8 encoding stays within a byte ceiling without cutting a code point.', purposeZh: '把 text 拆成有序 chunk；每个 chunk 的 UTF-8 encoding 不超过 byte ceiling，且不会切断 code point。', quickStart: "import { splitUtf8 } from '@migaia/utils'\n\nconst text = '订单已创建：Ada'\nconst chunks = splitUtf8(text, 8)\nconsole.log(chunks) // 每个 chunk 不超过 8 bytes，中文 code point 不会被拆开", useEn: 'A string payload must respect a byte-oriented message limit.', useZh: 'string payload 必须遵守 byte-oriented message limit。', avoidEn: 'The channel accepts the complete payload or requires streaming backpressure instead of eager chunk arrays.', avoidZh: 'channel 可接受完整 payload，或需要 streaming backpressure 而不是 eager chunk array。' }),
  'utils:bytes:bytesToBase64': utilsGuide({ purposeEn: 'Encodes bytes as portable Base64 text without leaking platform-specific Buffer ownership into callers.', purposeZh: '把 bytes 编码为 portable Base64 text，不向 caller 泄漏 platform-specific Buffer ownership。', quickStart: "import { bytesToBase64 } from '@migaia/utils'\n\nconst bytes = new Uint8Array([65, 100, 97])\nconst encoded = bytesToBase64(bytes)\nconsole.log(encoded) // QWRh：可放入只接受文本的 JSON 或 storage field", useEn: 'Binary data must enter a text-only JSON, attribute, or storage field.', useZh: 'binary data 需要进入 text-only JSON、attribute 或 storage field。', avoidEn: 'The boundary accepts bytes directly, where Base64 would add size and allocation overhead.', avoidZh: 'boundary 可直接接受 bytes；Base64 只会增加体积与 allocation。' }),
  'utils:bytes:base64ToBytes': utilsGuide({ purposeEn: 'Decodes Base64 text into a fresh Uint8Array through one runtime-neutral compatibility path.', purposeZh: '通过统一 runtime-neutral compatibility path 把 Base64 text 解码成新的 Uint8Array。', quickStart: "import { base64ToBytes } from '@migaia/utils'\n\nconst encoded = 'QWRh'\nconst bytes = base64ToBytes(encoded)\nconsole.log(bytes) // Uint8Array [65, 100, 97]：恢复后交给 byte sink", useEn: 'A text-only boundary returns Base64 that must become binary data.', useZh: 'text-only boundary 返回 Base64，需要恢复成 binary data。', avoidEn: 'The input uses Base64URL or another alphabet that has not been normalized.', avoidZh: 'input 使用尚未 normalize 的 Base64URL 或其他 alphabet。' }),
  'utils:bytes:streamBase64Chunks': utilsGuide({ purposeEn: 'Incrementally transforms byte chunks into correctly aligned Base64 text chunks while retaining incomplete three-byte groups between writes.', purposeZh: '增量地把 byte chunk 转成正确对齐的 Base64 text chunk，并在 write 之间保留不足三 byte 的尾部。', quickStart: "import { streamBase64Chunks } from '@migaia/utils'\n\nasync function* source() {\n  yield new Uint8Array([65, 100])\n  yield new Uint8Array([97])\n}\nfor await (const text of streamBase64Chunks(source())) console.log(text) // QWRh：流式输出仍保持 Base64 对齐", useEn: 'Large or streamed binary input must be Base64-encoded without one full-buffer allocation.', useZh: '大型或 streamed binary input 需要 Base64 encoding，且不能一次分配完整 buffer。', avoidEn: 'The input is already fully buffered and small enough for bytesToBase64.', avoidZh: 'input 已完整 buffered，且足够小，可直接使用 bytesToBase64。' }),
  'utils:bytes:isUint8Array': utilsGuide({ purposeEn: 'Checks the concrete Uint8Array byte-view contract used by binary APIs.', purposeZh: '检查 binary API 使用的具体 Uint8Array byte-view contract。', quickStart: "import { isUint8Array } from '@migaia/utils'\n\nconst value: unknown = new Uint8Array([1, 2])\nif (isUint8Array(value)) console.log(value.byteLength) // 2：通过 guard 后才能按 Uint8Array 使用", useEn: 'Unknown input must be narrowed before binary operations.', useZh: 'unknown input 在 binary operation 前需要窄化。', avoidEn: 'Any ArrayBufferView is acceptable; this predicate intentionally rejects other typed arrays.', avoidZh: '任意 ArrayBufferView 都可接受；该 predicate 会刻意拒绝其他 typed array。' }),
  'utils:bytes:isArrayBuffer': utilsGuide({ purposeEn: 'Checks ArrayBuffer identity across the supported runtime boundary before creating or transferring a view.', purposeZh: '在创建或 transfer view 前检查受支持 runtime boundary 中的 ArrayBuffer identity。', quickStart: "import { isArrayBuffer } from '@migaia/utils'\n\nconst value: unknown = new ArrayBuffer(4)\nconst bytes = isArrayBuffer(value) ? new Uint8Array(value) : undefined\nconsole.log(bytes?.byteLength) // 4：确认是 ArrayBuffer 后再创建 view", useEn: 'Unknown input may own a transferable raw byte buffer.', useZh: 'unknown input 可能拥有 transferable raw byte buffer。', avoidEn: 'SharedArrayBuffer or a typed-array view should also be accepted.', avoidZh: 'SharedArrayBuffer 或 typed-array view 也应该被接受。' }),
  'utils:config:combineConfig': utilsGuide({ purposeEn: 'Combines ordered configuration layers with explicit merge profiles, deletion markers, descriptor safety, and immutable output.', purposeZh: '按顺序组合 configuration layer，并提供显式 merge profile、deletion marker、descriptor safety 与 immutable output。', quickStart: "import { combineConfig } from '@migaia/utils'\n\nconst defaults = { timeoutMs: 1_000, theme: 'light' }\nconst environment = { timeoutMs: 2_000 }\nconst user = { theme: 'dark' }\nconst config = combineConfig(defaults, environment, user)\nconsole.log(config) // { timeoutMs: 2000, theme: 'dark' }：后层覆盖前层", useEn: 'Defaults, environment policy, and user overrides require one deterministic precedence contract.', useZh: 'defaults、environment policy 与 user override 需要统一 deterministic precedence contract。', avoidEn: 'A shallow object spread fully expresses the accepted ownership and deletion behavior.', avoidZh: '简单 object spread 已能完整表达 ownership 与 deletion behavior。' }),
  'utils:config:patchConfig': utilsGuide({ purposeEn: 'Applies one configuration patch under the selected profile without mutating either input object.', purposeZh: '按所选 profile 应用单个 configuration patch，且不修改任一 input object。', quickStart: "import { patchConfig } from '@migaia/utils'\n\nconst current = { timeoutMs: 1_000, retries: 2 }\nconst next = patchConfig(current, { timeoutMs: 2_000 })\nconsole.log(current.timeoutMs, next.timeoutMs) // 1000 2000：原配置不变，返回新快照", useEn: 'A live configuration snapshot must derive a new value from one patch.', useZh: 'live configuration snapshot 需要从单个 patch 派生新值。', avoidEn: 'The target is intentionally mutable or several precedence layers should be combined at once.', avoidZh: 'target 刻意允许 mutable，或需要一次组合多个 precedence layer。' }),
  'utils:config:ownConfig': utilsGuide({ purposeEn: 'Creates an owned configuration snapshot so later caller mutation cannot change admitted behavior.', purposeZh: '创建 owned configuration snapshot，避免 caller 后续 mutation 改变已 admission 的行为。', quickStart: "import { ownConfig } from '@migaia/utils'\n\nconst options = { retry: { maxAttempts: 2 } }\nconst owned = ownConfig(options)\noptions.retry.maxAttempts = 9\nconsole.log(owned.retry.maxAttempts) // 2：owner 保存自己的配置快照", useEn: 'A constructor must capture caller-supplied configuration at its ownership boundary.', useZh: 'constructor 需要在 ownership boundary 捕获 caller-supplied configuration。', avoidEn: 'Live mutation of the same configuration object is an intentional public contract.', avoidZh: '同一 configuration object 的 live mutation 是刻意 public contract。' }),
  'utils:config:readonlyConfig': utilsGuide({ purposeEn: 'Exposes a recursively read-only configuration view that rejects writes while retaining safe reads.', purposeZh: '公开 recursively read-only configuration view，拒绝 write，同时保留 safe read。', quickStart: "import { readonlyConfig } from '@migaia/utils'\n\nconst owned = { retry: { maxAttempts: 2 } }\nconst publicConfig = readonlyConfig(owned)\nconsole.log(publicConfig.retry.maxAttempts) // 2：可读但不能通过该视图修改 owner state", useEn: 'Consumers may inspect admitted configuration but must not mutate owner state.', useZh: 'consumer 可以检查 admitted configuration，但不能修改 owner state。', avoidEn: 'A plain immutable snapshot is enough and proxy write diagnostics are unnecessary.', avoidZh: 'plain immutable snapshot 已足够，且不需要 proxy write diagnostic。' }),
  'utils:config:parseConfigPath': utilsGuide({ purposeEn: 'Parses a validated dotted or bracketed configuration path into safe traversal segments.', purposeZh: '把经过校验的 dotted 或 bracketed configuration path 解析为 safe traversal segment。', quickStart: "import { parseConfigPath } from '@migaia/utils'\n\nconst segments = parseConfigPath('transport.retry.maxAttempts')\nconsole.log(segments) // 安全 segment 交给后续配置读取", useEn: 'Configuration fields are addressed by a stable textual path.', useZh: 'configuration field 通过稳定 textual path 定位。', avoidEn: 'The path is already a trusted segment array or dynamic prototype traversal is expected.', avoidZh: 'path 已经是 trusted segment array，或刻意需要 dynamic prototype traversal。' }),
  'utils:config:readConfigPath': utilsGuide({ purposeEn: 'Reads a configuration value through validated own-property segments without invoking an unsafe traversal path.', purposeZh: '通过 validated own-property segment 读取 configuration value，不执行 unsafe traversal path。', quickStart: "import { readConfigPath } from '@migaia/utils'\n\nconst config = { request: { timeoutMs: 2_000 } }\nconst timeout = readConfigPath(config, 'request.timeoutMs')\nconsole.log(timeout) // 2000：按路径安全读取配置", useEn: 'Diagnostics, UI, or policy code needs a safe dynamic configuration lookup.', useZh: 'diagnostics、UI 或 policy code 需要 safe dynamic configuration lookup。', avoidEn: 'Static property access is available and clearer at the call site.', avoidZh: 'call site 可使用更清晰的 static property access。' }),
  'utils:config:CONFIG_DELETE': utilsGuide({ purposeEn: 'Provides the explicit deletion sentinel understood by configuration merging, distinguishing removal from an undefined value.', purposeZh: '提供 configuration merge 识别的显式 deletion sentinel，把 removal 与 undefined value 区分开。', quickStart: "import { CONFIG_DELETE, patchConfig } from '@migaia/utils'\n\nconst current = { legacy: true }\nconst next = patchConfig(current, { legacy: CONFIG_DELETE })\nconsole.log(next) // {}：显式 sentinel 删除 inherited key，而不是写入 undefined", useEn: 'An override layer must remove an inherited key rather than replace its value.', useZh: 'override layer 需要删除 inherited key，而不是替换其 value。', avoidEn: 'Undefined already has the intended domain meaning and the field should remain present.', avoidZh: 'undefined 已具有预期 domain meaning，且 field 应继续存在。' }),
  'utils:config:ConfigProfile': utilsGuide({ purposeEn: 'Names the canonical merge profiles so callers select documented configuration semantics instead of ad hoc booleans.', purposeZh: '命名规范 merge profile，让 caller 选择已文档化的 configuration semantics，而不是拼装 ad hoc boolean。', quickStart: "import { ConfigProfile, patchConfig } from '@migaia/utils'\n\nconst current = { retry: { maxAttempts: 2 } }\nconst update = { retry: { timeoutMs: 2_000 } }\nconst next = patchConfig(current, update, ConfigProfile.deep)\nconsole.log(next)", useEn: 'The merge boundary must choose a stable shallow or deep policy.', useZh: 'merge boundary 需要选择稳定 shallow 或 deep policy。', avoidEn: 'A domain-specific reconciliation algorithm is required.', avoidZh: '需要 domain-specific reconciliation algorithm。' }),
  'utils:error:attachErrorIdentity': utilsGuide({ purposeEn: 'Adds stable source and code fields to an existing native Error without replacing its class, message, stack, or identity.', purposeZh: '给现有 native Error 增加稳定 source 与 code field，不替换其 class、message、stack 或 identity。', quickStart: "import { attachErrorIdentity } from '@migaia/utils'\n\nthrow attachErrorIdentity(new TypeError('invalid value'), { source: '@migaia/example', code: 'INVALID_VALUE' })", useEn: 'A boundary error must remain instanceof its native type while gaining machine-readable ownership.', useZh: 'boundary error 必须保留 native instanceof，同时获得 machine-readable ownership。', avoidEn: 'Constructing a new domain error is allowed and native identity does not matter.', avoidZh: '允许构造新的 domain error，且 native identity 不重要。' }),
  'utils:error:attachSecondaryErrors': utilsGuide({ purposeEn: 'Attaches cleanup or rollback failures as secondary evidence without replacing the primary error.', purposeZh: '把 cleanup 或 rollback failure 附加为 secondary evidence，不替换 primary error。', quickStart: "import { attachSecondaryErrors } from '@migaia/utils'\n\nconst primaryError = new Error('request failed')\nconst cleanupErrors = [new Error('cleanup failed')]\nthrow attachSecondaryErrors(primaryError, cleanupErrors)", useEn: 'An operation failed and its containment path also produced failures that must remain reachable.', useZh: 'operation 已失败，containment path 又产生必须保持可达的 failure。', avoidEn: 'There is no primary failure and all errors have equal aggregate status.', avoidZh: '不存在 primary failure，且所有 error 都具有同等 aggregate status。' }),
  'utils:error:combineErrors': utilsGuide({ purposeEn: 'Returns the primary error unchanged when possible and combines additional failures without severing cause or AggregateError reachability.', purposeZh: '尽可能原样返回 primary error，并组合 additional failure，同时保持 cause 或 AggregateError 可达。', quickStart: "import { combineErrors } from '@migaia/utils'\n\nconst primary = new Error('request failed')\nconst cleanupErrors = [new Error('cleanup failed')]\nconst failure = combineErrors(primary, cleanupErrors)\nconsole.error(failure)", useEn: 'A failure boundary must preserve primary precedence and expose every secondary failure.', useZh: 'failure boundary 需要保留 primary precedence，并公开每个 secondary failure。', avoidEn: 'Only one failure exists or ordering between failures is not meaningful.', avoidZh: '只有一个 failure，或 failure 之间没有 order meaning。' }),
  'utils:error:toError': utilsGuide({ purposeEn: 'Normalizes an unknown thrown value into an Error while retaining an existing Error instance unchanged.', purposeZh: '把 unknown thrown value 标准化为 Error；已有 Error instance 会原样保留。', quickStart: "import { toError } from '@migaia/utils'\n\nconst caught: unknown = 'network failed'\nconst error = toError(caught)\nconsole.error(error.message)", useEn: 'A catch boundary must report or aggregate values that may not be Error instances.', useZh: 'catch boundary 需要 report 或 aggregate 可能不是 Error instance 的 value。', avoidEn: 'The original non-Error value must remain the direct thrown contract.', avoidZh: '原始 non-Error value 必须继续作为直接 thrown contract。' }),
  'utils:error:safeErrorReason': utilsGuide({ purposeEn: 'Reads a usable human diagnostic from unknown failure input without letting hostile getters replace the original control flow.', purposeZh: '从 unknown failure input 安全读取可用 human diagnostic，避免 hostile getter 改变原始 control flow。', quickStart: "import { safeErrorReason } from '@migaia/utils'\n\nconst caught: unknown = new Error('network failed')\nconst reason = safeErrorReason(caught)\nconsole.log(reason)", useEn: 'Logging or diagnostics must describe arbitrary caught values safely.', useZh: 'logging 或 diagnostics 需要安全描述 arbitrary caught value。', avoidEn: 'Machine branching is required; use stable source and code instead of diagnostic text.', avoidZh: '需要 machine branching；应读取稳定 source 与 code，而不是 diagnostic text。' }),
  'utils:error:walkErrorCauses': utilsGuide({ purposeEn: 'Walks an Error cause chain with identity-cycle protection and a fixed traversal bound.', purposeZh: '以 identity-cycle protection 与固定 traversal bound 遍历 Error cause chain。', quickStart: "import { walkErrorCauses } from '@migaia/utils'\n\nconst error = new Error('outer', { cause: new Error('inner') })\nfor (const cause of walkErrorCauses(error)) console.log(cause.message)", useEn: 'Diagnostics or tests must find preserved original failures in wrappers.', useZh: 'diagnostics 或 test 需要在 wrapper 中找到被保留的 original failure。', avoidEn: 'AggregateError.errors must also be traversed; use a domain walker that includes aggregate branches.', avoidZh: '还需要遍历 AggregateError.errors；应使用包含 aggregate branch 的 domain walker。' }),
  'utils:error:isUtilsError': utilsGuide({ purposeEn: 'Detects the shared Utils coded-error shape without depending on same-realm instanceof.', purposeZh: '不依赖 same-realm instanceof，检测 shared Utils coded-error shape。', quickStart: "import { isUtilsError } from '@migaia/utils'\n\nconst error: unknown = new Error('invalid input')\nif (isUtilsError(error)) console.log(error.code)", useEn: 'A catch boundary needs stable Utils source/code handling across realms.', useZh: 'catch boundary 需要跨 realm 的稳定 Utils source/code handling。', avoidEn: 'The check is being used as proof that untrusted error fields are safe.', avoidZh: '把该 check 当作 untrusted error field 安全可信的证明。' }),
  'utils:error:isUtilsAbortError': utilsGuide({ purposeEn: 'Detects Utils cancellation while honoring the standard AbortError name across realm boundaries.', purposeZh: '跨 realm 检测 Utils cancellation，并遵守标准 AbortError name。', quickStart: "import { isUtilsAbortError } from '@migaia/utils'\n\nconst error: unknown = new DOMException('cancelled', 'AbortError')\nif (isUtilsAbortError(error)) console.log('请求已取消')", useEn: 'Expected cancellation must be separated from operational failures.', useZh: 'expected cancellation 需要与 operational failure 区分。', avoidEn: 'All AbortError values from every owner should be accepted without checking Utils ownership.', avoidZh: '需要接受所有 owner 的 AbortError，而不检查 Utils ownership。' }),
  'utils:error:isUtilsTimeoutError': utilsGuide({ purposeEn: 'Detects Utils deadline failures while honoring the standard TimeoutError name across realms.', purposeZh: '跨 realm 检测 Utils deadline failure，并遵守标准 TimeoutError name。', quickStart: "import { isUtilsTimeoutError } from '@migaia/utils'\n\nconst error: unknown = new Error('request timed out')\nif (isUtilsTimeoutError(error)) console.warn('retry after timeout')", useEn: 'Timeout handling differs from cancellation and other failures.', useZh: 'timeout handling 与 cancellation 及其他 failure 不同。', avoidEn: 'Any error after elapsed time should be guessed as a timeout.', avoidZh: '把 elapsed time 后的任意 error 猜测成 timeout。' }),
  'utils:error:UtilsError': utilsGuide({ purposeEn: 'Creates the base coded failure for Utils-owned contracts while preserving an optional original cause.', purposeZh: '创建 Utils-owned contract 的基础 coded failure，并保留 optional original cause。', quickStart: "import { UtilsError } from '@migaia/utils'\n\nconst cause = new Error('disk unavailable')\nconst failure = new UtilsError('INVALID_STATE', 'Operation is not available', cause)\nconsole.error(failure.cause) // 原始 failure 仍可追溯", useEn: 'A shared utility boundary needs a stable machine-readable failure.', useZh: 'shared utility boundary 需要稳定 machine-readable failure。', avoidEn: 'A native TypeError, RangeError, AbortError, or TimeoutError identity is the actual public contract.', avoidZh: '真正 public contract 是 native TypeError、RangeError、AbortError 或 TimeoutError identity。' }),
  'utils:error:UtilsAbortError': utilsGuide({ purposeEn: 'Represents Utils-owned cancellation with a standard AbortError name and reachable cause.', purposeZh: '以标准 AbortError name 与可达 cause 表示 Utils-owned cancellation。', quickStart: "import { UtilsAbortError } from '@migaia/utils'\n\nconst controller = new AbortController()\ncontroller.abort('user navigated away')\nconst failure = new UtilsAbortError(controller.signal.reason)\nconsole.log(failure.name, failure.cause)", useEn: 'A shared async utility terminates because its owner or caller aborted.', useZh: 'shared async utility 因 owner 或 caller abort 而终止。', avoidEn: 'The operation completed, failed normally, or merely timed out.', avoidZh: 'operation 已完成、正常失败，或只是 timeout。' }),
  'utils:error:UtilsTimeoutError': utilsGuide({ purposeEn: 'Represents a Utils-owned exceeded deadline with a standard TimeoutError name.', purposeZh: '以标准 TimeoutError name 表示 Utils-owned deadline 超限。', quickStart: "import { UtilsTimeoutError } from '@migaia/utils'\n\nconst timeoutMs = 5_000\nthrow new UtilsTimeoutError(timeoutMs)", useEn: 'A bounded async utility exhausts its declared deadline.', useZh: 'bounded async utility 用尽声明的 deadline。', avoidEn: 'The caller explicitly cancelled or the underlying operation failed before the deadline.', avoidZh: 'caller 显式取消，或 underlying operation 在 deadline 前失败。' }),
  'utils:function:once': utilsGuide({ purposeEn: 'Wraps a synchronous callable so only its first invocation executes and every later invocation returns the first result.', purposeZh: '包装 synchronous callable，只执行第一次 invocation，后续 invocation 都返回第一次 result。', quickStart: "import { once } from '@migaia/utils'\n\nlet calls = 0\nconst initialize = once(() => { calls += 1; return { id: 'client' } })\nconsole.log(initialize(), initialize(), calls) // 同一个结果，calls 为 1", useEn: 'Initialization or registration must have stable exactly-once execution in one owner.', useZh: 'initialization 或 registration 在单一 owner 中需要稳定 exactly-once execution。', avoidEn: 'Failures should permit another attempt or calls have different meaningful arguments.', avoidZh: 'failure 后应允许再次尝试，或不同 call argument 具有不同意义。' }),
  'utils:function:onceAsync': utilsGuide({ purposeEn: 'Shares the exact first Promise across concurrent and later calls, preventing duplicate asynchronous initialization.', purposeZh: '在 concurrent 与后续 call 之间共享完全相同的 first Promise，避免重复 asynchronous initialization。', quickStart: "import { onceAsync } from '@migaia/utils'\n\nlet connections = 0\nconst connectOnce = onceAsync(async () => { connections += 1; return { id: 'db' } })\nconst [first, second] = await Promise.all([connectOnce(), connectOnce()])\nconsole.log(first === second, connections) // true 1：并发调用共享同一个初始化 Promise", useEn: 'Concurrent callers must join one initialization and observe the same settlement.', useZh: 'concurrent caller 必须加入同一次 initialization，并观察同一个 settlement。', avoidEn: 'A rejected attempt should be evicted and retried automatically.', avoidZh: 'rejected attempt 应被 eviction 并自动 retry。' }),
  'utils:function:noop': utilsGuide({ purposeEn: 'Provides one stable no-operation callback for optional hooks and cleanup slots.', purposeZh: '为 optional hook 与 cleanup slot 提供统一稳定的 no-operation callback。', quickStart: "import { noop } from '@migaia/utils'\n\nconst options: { report?: (error: unknown) => void } = {}\nconst report = options.report ?? noop\nreport(new Error('ignored by this optional hook')) // fallback 不执行任何动作", useEn: 'An API requires a callable fallback with no behavior or allocation.', useZh: 'API 需要无行为、无 allocation 的 callable fallback。', avoidEn: 'Missing behavior should be observable, diagnosed, or rejected.', avoidZh: 'missing behavior 应被观察、诊断或拒绝。' }),
  'utils:function:inspectThenable': utilsGuide({ purposeEn: 'Inspects an unknown value for a callable then member once, preserving getter failure and receiver identity without assimilating it.', purposeZh: '只读取一次 unknown value 的 callable then member，保留 getter failure 与 receiver identity，但不执行 assimilation。', quickStart: "import { inspectThenable } from '@migaia/utils'\n\nconst value: unknown = { then(resolve: (result: string) => void) { resolve('ok') } }\nconst inspection = inspectThenable(value)\nconsole.log(inspection.kind) // 只分类，不会自动执行 then", useEn: 'Low-level promise interoperability must classify a hostile or foreign thenable safely.', useZh: 'low-level promise interoperability 需要安全分类 hostile 或 foreign thenable。', avoidEn: 'Normal application code only needs Promise.resolve.', avoidZh: '普通 application code 只需要 Promise.resolve。' }),
  'utils:function:probeThenable': utilsGuide({ purposeEn: 'Classifies a value as non-thenable, callable thenable, or failed then lookup without throwing during probing.', purposeZh: '把 value 分类为 non-thenable、callable thenable 或 then lookup failure，probe 期间不抛出。', quickStart: "import { probeThenable } from '@migaia/utils'\n\nconst value: unknown = { id: 'plain' }\nconst probe = probeThenable(value)\nconsole.log(probe.kind) // non-thenable：普通对象不会被当作 Promise-like", useEn: 'A runtime boundary needs explicit non-throwing thenable admission.', useZh: 'runtime boundary 需要显式 non-throwing thenable admission。', avoidEn: 'The value is already typed as PromiseLike and getter hazards are outside scope.', avoidZh: 'value 已 typed 为 PromiseLike，且 getter hazard 不在 scope。' }),
  'utils:function:assimilateCapturedThen': utilsGuide({ purposeEn: 'Assimilates a previously captured then function with its original receiver, single-settlement protection, and exception containment.', purposeZh: '使用原始 receiver assimilation 已捕获的 then function，并提供 single-settlement protection 与 exception containment。', quickStart: "import { assimilateCapturedThen, inspectThenable } from '@migaia/utils'\n\nconst value: unknown = { then(resolve: (result: string) => void) { resolve('ok') } }\nconst inspection = inspectThenable(value)\nconst promise = assimilateCapturedThen(value, inspection.then)\nconsole.log(await promise) // ok：复用已捕获的 then，不重复读取 getter", useEn: 'Then lookup and then invocation must be separated without reading a hostile getter twice.', useZh: 'then lookup 与 then invocation 需要分离，且不能重复读取 hostile getter。', avoidEn: 'The then function was not captured by a compatible inspection boundary.', avoidZh: 'then function 不是由 compatible inspection boundary 捕获。' }),
  'utils:function:observeThenableRejection': utilsGuide({ purposeEn: 'Attaches rejection observation to a thenable without changing its identity or turning observation into ownership of its result.', purposeZh: '给 thenable 附加 rejection observation，不改变其 identity，也不把 observation 变成 result ownership。', quickStart: "import { observeThenableRejection } from '@migaia/utils'\n\nconst task = Promise.reject(new Error('background sync failed'))\nconst report = (error: unknown) => console.error('observed', error)\nobserveThenableRejection(task, report)", useEn: 'Fire-and-observe work must never create an unhandled rejection.', useZh: 'fire-and-observe work 不得产生 unhandled rejection。', avoidEn: 'The caller must await, transform, cancel, or otherwise own the task result.', avoidZh: 'caller 需要 await、transform、cancel 或以其他方式拥有 task result。' }),
  'utils:function:ThenableProbeKind': utilsGuide({ purposeEn: 'Names the stable outcomes produced by thenable probing so callers do not branch on ad hoc strings.', purposeZh: '命名 thenable probing 的稳定 outcome，避免 caller 根据 ad hoc string 分支。', quickStart: "import { ThenableProbeKind, probeThenable } from '@migaia/utils'\n\nconst probe = probeThenable({ id: 'plain' })\nconst report = (error: unknown) => console.error(error)\nif (probe.kind === ThenableProbeKind.failed) report(probe.error)", useEn: 'Code consumes inspectThenable or probeThenable classification.', useZh: '代码需要消费 inspectThenable 或 probeThenable classification。', avoidEn: 'The value can be handled directly with ordinary await semantics.', avoidZh: 'value 可直接用普通 await semantics 处理。' })
}

/** Human-maintained number, object, and immutable object-path guides. */
const dataUtilsApiGuides: Readonly<
  Record<string, Readonly<Record<IGuideLocale, IApiGuide>>>
> = {
  'utils:number:createNumberFormatter': utilsGuide({ purposeEn: 'Creates a reusable locale-aware formatter that centralizes Intl.NumberFormat construction and all integer, percent, currency, and compact policies.', purposeZh: '创建可复用的 locale-aware formatter，集中拥有 Intl.NumberFormat construction 以及 integer、percent、currency 与 compact policy。', quickStart: "import { createNumberFormatter } from '@migaia/utils'\n\nconst numbers = createNumberFormatter({ locales: 'zh' })\nconsole.log(numbers.number(1234.5)) // 多次格式化复用同一 locale 与 formatting policy", useEn: 'Several values share the same locale and formatting policy.', useZh: '多个 value 共享相同 locale 与 formatting policy。', avoidEn: 'Only one value is formatted or the host already owns one Intl.NumberFormat instance.', avoidZh: '只格式化一个 value，或宿主已经拥有 Intl.NumberFormat instance。' }),
  'utils:number:formatNumber': utilsGuide({ purposeEn: 'Formats a finite numeric input with locale-aware decimal notation and the caller-selected Intl options.', purposeZh: '使用 locale-aware decimal notation 与 caller-selected Intl option 格式化 finite numeric input。', quickStart: "import { formatNumber } from '@migaia/utils'\n\nconst label = formatNumber(1234.5, { locales: 'zh' })", useEn: 'A general decimal value needs human-readable locale output.', useZh: 'general decimal value 需要 human-readable locale output。', avoidEn: 'The value represents currency, percent, an integer, or compact magnitude with a more specific semantic formatter.', avoidZh: 'value 表示 currency、percent、integer 或 compact magnitude，应使用更具体 semantic formatter。' }),
  'utils:number:formatInteger': utilsGuide({ purposeEn: 'Formats numeric input as a locale-aware integer using zero fractional digits unless explicitly overridden.', purposeZh: '把 numeric input 格式化为 locale-aware integer，默认不保留 fractional digit，除非显式覆盖。', quickStart: "import { formatInteger } from '@migaia/utils'\n\nconst count = formatInteger(1234, { locales: 'en-US' })", useEn: 'A count or whole-unit quantity must read naturally in the selected locale.', useZh: 'count 或 whole-unit quantity 需要按所选 locale 自然显示。', avoidEn: 'Fractional precision carries domain meaning.', avoidZh: 'fractional precision 具有 domain meaning。' }),
  'utils:number:formatPercent': utilsGuide({ purposeEn: 'Formats a ratio with locale-aware percent notation, where 1 represents one hundred percent.', purposeZh: '使用 locale-aware percent notation 格式化 ratio，其中 1 表示百分之百。', quickStart: "import { formatPercent } from '@migaia/utils'\n\nconst completion = formatPercent(0.625, { locales: 'zh' })", useEn: 'A normalized ratio should be displayed as a percentage.', useZh: 'normalized ratio 需要显示为 percentage。', avoidEn: 'The input is already expressed in percentage points and has not been normalized.', avoidZh: 'input 已经是 percentage point，且尚未 normalize。' }),
  'utils:number:formatCurrency': utilsGuide({ purposeEn: 'Formats a monetary amount with an explicit ISO currency code and locale-aware currency conventions.', purposeZh: '使用显式 ISO currency code 与 locale-aware currency convention 格式化 monetary amount。', quickStart: "import { formatCurrency } from '@migaia/utils'\n\nconst price = formatCurrency(1234.5, 'CNY', { locales: 'zh' })", useEn: 'A monetary value must expose its currency and locale-specific presentation.', useZh: 'monetary value 需要公开 currency 与 locale-specific presentation。', avoidEn: 'The value has no currency semantics or the currency code is unknown.', avoidZh: 'value 没有 currency semantics，或 currency code 未知。' }),
  'utils:number:formatCompactNumber': utilsGuide({ purposeEn: 'Formats large magnitudes with locale-aware compact notation such as 1.2K or its local equivalent.', purposeZh: '把大数值格式化为 locale-aware compact notation，例如 1.2K 或对应本地表达。', quickStart: "import { formatCompactNumber } from '@migaia/utils'\n\nconst audience = formatCompactNumber(12500, { locales: 'en-US' })", useEn: 'Space-constrained summaries need approximate readable magnitude.', useZh: 'space-constrained summary 需要近似、易读的 magnitude。', avoidEn: 'Exact digits are required for accounting, limits, identifiers, or accessibility text.', avoidZh: 'accounting、limit、identifier 或 accessibility text 需要精确 digit。' }),
  'utils:object:isPlainObject': utilsGuide({ purposeEn: 'Accepts only ordinary record-like objects and rejects arrays, dates, class instances, and other specialized prototypes.', purposeZh: '只接受 ordinary record-like object，拒绝 array、date、class instance 与其他 specialized prototype。', quickStart: "import { isPlainObject } from '@migaia/utils'\n\nconst value: unknown = { id: 1, name: 'Ada' }\nif (isPlainObject(value)) console.log(value.name) // Ada：通过 guard 后按普通 record 处理", useEn: 'A merge, codec, or traversal rule is valid only for plain records.', useZh: 'merge、codec 或 traversal rule 只适用于 plain record。', avoidEn: 'Any object, iterable, array, or class instance is a valid domain value.', avoidZh: '任意 object、iterable、array 或 class instance 都是有效 domain value。' }),
  'utils:object:probeProperty': utilsGuide({ purposeEn: 'Reads one property exactly once and returns value, missing, or failed as data instead of allowing a hostile getter to escape.', purposeZh: '只读取一次 property，并把 value、missing 或 failed 作为 data 返回，避免 hostile getter 逃逸。', quickStart: "import { probeProperty } from '@migaia/utils'\n\nconst input: unknown = { name: 'Ada' }\nconst result = probeProperty(input, 'name')\nif (result.kind === 'value') console.log(result.value) // Ada：getter 结果作为 data 返回", useEn: 'Unknown or cross-boundary objects may contain throwing accessors.', useZh: 'unknown 或 cross-boundary object 可能包含 throwing accessor。', avoidEn: 'Normal typed property access is trusted and a thrown getter should propagate directly.', avoidZh: '普通 typed property access 可信，且 getter failure 应直接传播。' }),
  'utils:object:snapshotOwnDescriptors': utilsGuide({ purposeEn: 'Captures an object own-property descriptor inventory without invoking accessors, reporting descriptor-read failures separately.', purposeZh: '不调用 accessor 地捕获 object own-property descriptor inventory，并单独报告 descriptor-read failure。', quickStart: "import { snapshotOwnDescriptors } from '@migaia/utils'\n\nconst value: unknown = { id: 1, get name() { return 'Ada' } }\nconst snapshot = snapshotOwnDescriptors(value)\nconsole.log(snapshot) // 只记录 descriptor，不执行 name getter", useEn: 'A diagnostic, clone, or admission boundary must inspect ownership safely.', useZh: 'diagnostic、clone 或 admission boundary 需要安全检查 ownership。', avoidEn: 'Prototype properties or evaluated accessor values are intentionally required.', avoidZh: '刻意需要 prototype property 或已执行的 accessor value。' }),
  'utils:object:identitySnapshot': utilsGuide({ purposeEn: 'Selects the zero-copy branch of a configurable snapshot policy; calling it on its own adds no runtime value.', purposeZh: '为可配置 snapshot policy 选择零拷贝分支；单独调用没有运行时价值。', quickStart: "import { identitySnapshot, immutableSnapshot } from '@migaia/utils'\n\nconst snapshotPolicy = { isolated: immutableSnapshot, shared: identitySnapshot } as const\nconst source = { retry: 2 }\nconst retained = snapshotPolicy.shared(source)\nsource.retry = 3\nretained.retry // 3: same object", useEn: 'A trusted in-process policy slot must explicitly accept shared ownership for identity-sensitive or uncloneable values.', useZh: '可信进程内的策略槽需要为身份敏感或不可克隆数据明确接受共享所有权。', avoidEn: 'Mutation isolation, historical snapshots, serialization safety, or cross-boundary transfer is required.', avoidZh: '需要修改隔离、历史快照、序列化安全或跨边界传输。' }),
  'utils:object:immutableSnapshot': utilsGuide({ purposeEn: 'Creates a detached recursively immutable snapshot for supported structured data, preserving domain values such as Date through the canonical clone path.', purposeZh: '为受支持 structured data 创建 detached recursively immutable snapshot，并通过 canonical clone path 保留 Date 等 domain value。', quickStart: "import { immutableSnapshot } from '@migaia/utils'\n\nconst user = { id: 1, name: 'Ada' }\nconst snapshot = immutableSnapshot({ user, createdAt: new Date() })\nuser.name = 'Grace'\nconsole.log(snapshot.user.name) // Ada：发布的快照与原始对象隔离", useEn: 'Published state must not change when either producer or consumer mutates its original graph.', useZh: 'published state 不得因 producer 或 consumer 修改原始 graph 而变化。', avoidEn: 'The graph contains unsupported capabilities or identity sharing is the intended contract.', avoidZh: 'graph 包含 unsupported capability，或 identity sharing 是预期 contract。' }),
  'utils:object:diagnosticSnapshot': utilsGuide({ purposeEn: 'Produces a best-effort immutable diagnostic value plus explicit paths for accessors, read failures, and unsupported members.', purposeZh: '生成 best-effort immutable diagnostic value，并显式列出 accessor、read failure 与 unsupported member 的 path。', quickStart: "import { diagnosticSnapshot } from '@migaia/utils'\n\nconst input = { user: { name: 'Ada' }, handler: () => undefined }\nconst { value, diagnostics } = diagnosticSnapshot(input)\nconsole.log(value, diagnostics) // 诊断数据和无法复制的路径分开返回", useEn: 'Logging or tracing must remain available even when part of an object graph cannot be safely copied.', useZh: '即使 object graph 部分内容无法安全复制，logging 或 tracing 仍必须可用。', avoidEn: 'The snapshot is used as authoritative business state or round-trip serialization.', avoidZh: 'snapshot 将用作 authoritative business state 或 round-trip serialization。' }),
  'utils:object:structuredDiagnosticSnapshot': utilsGuide({ purposeEn: 'Builds a structured-clone-oriented diagnostic snapshot while containing unsupported values and preserving a path-indexed diagnostic inventory.', purposeZh: '构建 structured-clone-oriented diagnostic snapshot，同时隔离 unsupported value，并保留 path-indexed diagnostic inventory。', quickStart: "import { structuredDiagnosticSnapshot } from '@migaia/utils'\n\nconst event = { type: 'sync', payload: { id: 1 }, callback: () => undefined }\nconst result = structuredDiagnosticSnapshot(event)\nconsole.log(result.value, result.diagnostics) // 可跨 structured-clone 边界传递诊断结果", useEn: 'Diagnostics must cross a Worker or other structured-clone boundary.', useZh: 'diagnostics 需要跨 Worker 或其他 structured-clone boundary。', avoidEn: 'The value remains local or unsupported fields must make the whole operation fail.', avoidZh: 'value 只在本地使用，或 unsupported field 必须让整个 operation 失败。' }),
  'utils:object-path:parseObjectPath': utilsGuide({ purposeEn: 'Parses a dotted or bracket-index path into a frozen safe segment tuple and rejects unsafe prototype-pollution segments.', purposeZh: '把 dotted 或 bracket-index path 解析为 frozen safe segment tuple，并拒绝 unsafe prototype-pollution segment。', quickStart: "import { parseObjectPath } from '@migaia/utils'\n\nconst path = parseObjectPath('user.tags.[0]')", useEn: 'A user-facing or configuration path must be validated once before traversal.', useZh: 'user-facing 或 configuration path 需要在 traversal 前统一校验。', avoidEn: 'The caller already owns a trusted typed segment tuple.', avoidZh: 'caller 已经拥有 trusted typed segment tuple。' }),
  'utils:object-path:probeObjectPath': utilsGuide({ purposeEn: 'Traverses a textual or tuple path once and returns value, missing, blocked, or failed without conflating those outcomes.', purposeZh: '只遍历一次 textual 或 tuple path，并返回 value、missing、blocked 或 failed，不混淆这些 outcome。', quickStart: "import { probeObjectPath } from '@migaia/utils'\n\nconst data = { user: { name: 'Ada' } }\nconst result = probeObjectPath(data, 'user.name')\nconsole.log(result) // { kind: 'value', value: 'Ada' }：可区分 missing 与读取失败", useEn: 'The caller needs precise diagnostics or policy for every traversal outcome.', useZh: 'caller 需要针对每种 traversal outcome 的精确 diagnostic 或 policy。', avoidEn: 'Only a value-or-undefined convenience read is needed.', avoidZh: '只需要 value-or-undefined convenience read。' }),
  'utils:object-path:probeObjectPathSegments': utilsGuide({ purposeEn: 'Traverses an already parsed segment tuple with the same value, missing, blocked, and failed result algebra.', purposeZh: '使用已解析 segment tuple traversal，并返回相同的 value、missing、blocked 与 failed result algebra。', quickStart: "import { parseObjectPath, probeObjectPathSegments } from '@migaia/utils'\n\nconst data = { user: { name: 'Ada' } }\nconst segments = parseObjectPath('user.name')\nconst result = probeObjectPathSegments(data, segments)\nconsole.log(result) // { kind: 'value', value: 'Ada' }：解析一次后可重复读取", useEn: 'One parsed path is reused across many reads or sits on a hot path.', useZh: '同一 parsed path 需要复用于多次 read，或位于 hot path。', avoidEn: 'The path is untrusted text that has not passed parseObjectPath.', avoidZh: 'path 是尚未经过 parseObjectPath 的 untrusted text。' }),
  'utils:object-path:get': utilsGuide({ purposeEn: 'Reads a nested value through the safe path contract and returns undefined for missing or blocked traversal.', purposeZh: '通过 safe path contract 读取 nested value，并在 missing 或 blocked traversal 时返回 undefined。', quickStart: "import { get } from '@migaia/utils'\n\nconst data = { user: { name: 'Ada' } }\nconst name = get(data, 'user.name')\nconsole.log(name) // Ada：只需要值时使用简洁读取", useEn: 'Application code needs a concise immutable nested read and does not need outcome diagnostics.', useZh: 'application code 需要简洁 immutable nested read，且不需要 outcome diagnostic。', avoidEn: 'Missing, blocked, failed, and present-undefined must be distinguished.', avoidZh: '需要区分 missing、blocked、failed 与 present-undefined。' }),
  'utils:object-path:set': utilsGuide({ purposeEn: 'Returns a structurally shared immutable update along one safe path while preserving untouched branch identities.', purposeZh: '沿 safe path 返回 structurally shared immutable update，并保留 untouched branch identity。', quickStart: "import { set } from '@migaia/utils'\n\nconst state = { user: { name: 'Ada' }, theme: 'dark' }\nconst next = set(state, 'user.name', 'Grace')\nconsole.log(state.user.name, next.user.name) // Ada Grace：输入未被修改", useEn: 'Nested state must be updated without mutating the input graph.', useZh: 'nested state 需要更新，但不能修改 input graph。', avoidEn: 'The path is missing, blocked, or the domain owner requires a transactional mutation API.', avoidZh: 'path missing、blocked，或 domain owner 要求 transactional mutation API。' }),
  'utils:object-path:createPathAccessor': utilsGuide({ purposeEn: 'Creates a stateful path accessor that owns safe get/set operations and optional missing, blocked, failed, read, and write observation hooks.', purposeZh: '创建 stateful path accessor，拥有 safe get/set operation，以及 optional missing、blocked、failed、read 与 write observation hook。', quickStart: "import { createPathAccessor } from '@migaia/utils'\n\nconst state = { count: 0 }\nconst audit = (event: unknown) => console.log('changed', event)\nconst accessor = createPathAccessor(state, { onSet: audit })\naccessor.set('count', 1)\nconsole.log(accessor.get('count')) // 1：同一个 root 和 observation policy 可复用", useEn: 'Many path operations share one root value and one observation policy.', useZh: '多次 path operation 共享同一 root value 与 observation policy。', avoidEn: 'A single stateless get or set call is clearer.', avoidZh: '单次 stateless get 或 set call 更清晰。' })
}

/** Human-maintained async-control, string, and value classification guides. */
const controlUtilsApiGuides: Readonly<
  Record<string, Readonly<Record<IGuideLocale, IApiGuide>>>
> = {
  'utils:promise:deferred': utilsGuide({ purposeEn: 'Creates a Promise together with externally owned resolve and reject controls for bridging callback or event completion.', purposeZh: '创建 Promise 及 externally owned resolve/reject control，用于桥接 callback 或 event completion。', quickStart: "import { deferred } from '@migaia/utils'\n\nconst task = deferred<number>()\nsetTimeout(() => task.resolve(42), 0) // callback/event 完成时由 producer resolve\nconsole.log(await task.promise) // 42：consumer 等待同一个 Promise", useEn: 'A non-Promise producer completes an operation later through callbacks or events.', useZh: 'non-Promise producer 通过 callback 或 event 在稍后完成 operation。', avoidEn: 'An async function or existing Promise can express the ownership directly.', avoidZh: 'async function 或已有 Promise 可以直接表达 ownership。' }),
  'utils:promise:toPromise': utilsGuide({ purposeEn: 'Invokes a synchronous-or-thenable producer and guarantees that both thrown errors and returned thenables settle through one Promise boundary.', purposeZh: '调用 synchronous-or-thenable producer，并保证 thrown error 与 returned thenable 都通过统一 Promise boundary settle。', quickStart: "import { toPromise } from '@migaia/utils'\n\nconst cache = new Map([['user:1', { name: 'Ada' }]])\nconst key = 'user:1'\nconst value = await toPromise(() => cache.get(key))\nconsole.log(value) // { name: 'Ada' }：同步返回也统一进入 Promise boundary", useEn: 'A callback may return synchronously, return a thenable, or throw before returning.', useZh: 'callback 可能同步返回、返回 thenable，或在返回前抛错。', avoidEn: 'The producer is already an invoked Promise and no synchronous throw boundary remains.', avoidZh: 'producer 已经是 invoked Promise，且不存在 synchronous throw boundary。' }),
  'utils:promise:sleep': utilsGuide({ purposeEn: 'Waits through the selected scheduler with optional cancellation and deterministic cleanup of the owned timer.', purposeZh: '通过所选 scheduler 等待，并支持 optional cancellation 与 owned timer 的 deterministic cleanup。', quickStart: "import { sleep, systemScheduler } from '@migaia/utils'\n\nconst controller = new AbortController()\nawait sleep(10, { signal: controller.signal, scheduler: systemScheduler })\nconsole.log('delay finished') // timer 完成后自动清理", useEn: 'Backoff, pacing, or tests need an abortable scheduler-owned delay.', useZh: 'backoff、pacing 或 test 需要 abortable scheduler-owned delay。', avoidEn: 'A busy wait, frame callback, or deadline wrapper owns the actual timing semantics.', avoidZh: '实际 timing semantics 由 busy wait、frame callback 或 deadline wrapper 拥有。' }),
  'utils:promise:raceWithAbort': utilsGuide({ purposeEn: 'Runs one operation against composed abort signals, preserves the winning reason, and contains late rejection and cleanup failures by policy.', purposeZh: '让单个 operation 对 composed abort signal 运行，保留 winning reason，并按 policy 隔离 late rejection 与 cleanup failure。', quickStart: "import { raceWithAbort } from '@migaia/utils'\n\nconst controller = new AbortController()\nconst load = async ({ signal }: { signal: AbortSignal }) => {\n  if (signal.aborted) throw signal.reason\n  return { id: 'user:1' }\n}\nconst result = await raceWithAbort(({ signal }) => load({ signal }), { signal: controller.signal })\nconsole.log(result) // { id: 'user:1' }：完成或取消只保留一个明确结果", useEn: 'An operation must stop observing results when its caller or owner cancels.', useZh: 'caller 或 owner cancellation 后，operation 必须停止观察 result。', avoidEn: 'The underlying operation cannot cooperate and abandoning its result would leak an externally owned resource.', avoidZh: 'underlying operation 无法 cooperate，且放弃 result 会泄漏 externally owned resource。' }),
  'utils:promise:withTimeout': utilsGuide({ purposeEn: 'Runs an abort-aware operation under a scheduler-owned deadline and distinguishes timeout from external cancellation.', purposeZh: '让 abort-aware operation 在 scheduler-owned deadline 下运行，并区分 timeout 与 external cancellation。', quickStart: "import { sleep, systemScheduler, withTimeout } from '@migaia/utils'\n\nconst load = async ({ signal }: { signal: AbortSignal }) => {\n  await sleep(1, { signal, scheduler: systemScheduler })\n  return 'ready'\n}\nconst result = await withTimeout(({ signal }) => load({ signal }), { timeoutMs: 5_000 })\nconsole.log(result) // ready：成功结果与超时错误明确区分", useEn: 'One async operation must have a hard bounded deadline with late-failure containment.', useZh: '单个 async operation 需要 hard bounded deadline 与 late-failure containment。', avoidEn: 'The operation has its own authoritative deadline or timeout cannot safely abandon its side effects.', avoidZh: 'operation 已拥有 authoritative deadline，或 timeout 无法安全放弃其 side effect。' }),
  'utils:promise:retry': utilsGuide({ purposeEn: 'Retries an operation under explicit maximum attempts, retry predicate, delay policy, scheduler, and cancellation controls.', purposeZh: '按显式 max attempt、retry predicate、delay policy、scheduler 与 cancellation control 重试 operation。', quickStart: "import { retry } from '@migaia/utils'\n\nlet attempts = 0\nconst load = async () => {\n  attempts += 1\n  if (attempts < 2) throw new Error('temporary failure')\n  return 'ready'\n}\nconst shouldRetry = (error: unknown) => error instanceof Error\nconst result = await retry(load, { maxAttempts: 3, shouldRetry, delay: 1 })\nconsole.log(result, attempts) // ready 2：仅对可重试失败再次执行", useEn: 'A repeat-safe transient operation needs a bounded observable retry policy.', useZh: 'repeat-safe transient operation 需要 bounded observable retry policy。', avoidEn: 'The operation is not idempotent, the failure is permanent, or retries belong to a higher orchestration boundary.', avoidZh: 'operation 非 idempotent、failure permanent，或 retry 应由更高 orchestration boundary 拥有。' }),
  'utils:promise:createConcurrencyLimiter': utilsGuide({ purposeEn: 'Creates a FIFO task limiter with bounded active work, abort-aware queue admission, and disposal that waits for admitted work.', purposeZh: '创建 FIFO task limiter，限制 active work，支持 abort-aware queue admission，并在 dispose 时等待 admitted work。', quickStart: "import { createConcurrencyLimiter } from '@migaia/utils'\n\nconst limiter = createConcurrencyLimiter({ concurrency: 2 })\nconst task = () => Promise.resolve('processed')\nconst result = await limiter.run(task)\nconsole.log(result) // processed：任务通过 limiter 后才占用并发额度\nawait limiter.dispose() // 等待已接纳任务并释放 limiter", useEn: 'Many independent tasks must share a fixed resource concurrency budget.', useZh: '多个 independent task 需要共享固定 resource concurrency budget。', avoidEn: 'Task ordering, priorities, rate limits, or distributed capacity require a richer scheduler.', avoidZh: 'task ordering、priority、rate limit 或 distributed capacity 需要更完整 scheduler。' }),
  'utils:promise:createAbortTimeoutSignal': utilsGuide({ purposeEn: 'Composes an optional external signal and deadline into one owned signal plus an explicit disposer for timer and listener cleanup.', purposeZh: '把 optional external signal 与 deadline 组合成一个 owned signal，并提供显式 disposer 清理 timer 与 listener。', quickStart: "import { createAbortTimeoutSignal, sleep, systemScheduler } from '@migaia/utils'\n\nconst controller = new AbortController()\nconst control = createAbortTimeoutSignal({ signal: controller.signal, timeoutMs: 1_000 })\nconst work = async (signal: AbortSignal) => {\n  await sleep(1, { signal, scheduler: systemScheduler })\n  return 'done'\n}\ntry { console.log(await work(control.signal)) } finally { control.dispose() }", useEn: 'Several sibling operations must observe one cancellation and timeout decision.', useZh: '多个 sibling operation 需要观察同一个 cancellation 与 timeout decision。', avoidEn: 'Only one operation needs withTimeout or raceWithAbort, which already owns cleanup.', avoidZh: '只有一个 operation 需要 withTimeout 或 raceWithAbort，后者已拥有 cleanup。' }),
  'utils:promise:createManualScheduler': utilsGuide({ purposeEn: 'Creates deterministic virtual time whose queued timers advance only when the test or host explicitly moves the clock.', purposeZh: '创建 deterministic virtual time；queued timer 只在 test 或 host 显式推进 clock 时运行。', quickStart: "import { createManualScheduler, sleep } from '@migaia/utils'\n\nconst scheduler = createManualScheduler()\nconst pending = sleep(100, { scheduler })\nscheduler.advance(100)\nconsole.log(await pending) // 虚拟时钟推进后完成，不依赖真实等待", useEn: 'Tests or simulations need exact control over deadlines, backoff, and timer order.', useZh: 'test 或 simulation 需要精确控制 deadline、backoff 与 timer order。', avoidEn: 'Production work should follow real host time.', avoidZh: 'production work 应遵循真实 host time。' }),
  'utils:promise:systemScheduler': utilsGuide({ purposeEn: 'Provides the canonical real-time scheduler backed by host timers and the monotonic time source available to the runtime.', purposeZh: '提供规范 real-time scheduler，由 host timer 与 runtime 可用的 monotonic time source 支撑。', quickStart: "import { sleep, systemScheduler } from '@migaia/utils'\n\nawait sleep(100, { scheduler: systemScheduler })", useEn: 'Production async controls need the default host time authority explicitly.', useZh: 'production async control 需要显式使用 default host time authority。', avoidEn: 'Deterministic tests or another owner controls virtual time.', avoidZh: 'deterministic test 或其他 owner 控制 virtual time。' }),
  'utils:promise:hostRethrowReporter': utilsGuide({ purposeEn: 'Reports contained late or cleanup failures through a host rethrow boundary so they remain observable instead of being silently swallowed.', purposeZh: '通过 host rethrow boundary 报告已隔离的 late 或 cleanup failure，避免静默吞掉。', quickStart: "import { hostRethrowReporter, withTimeout } from '@migaia/utils'\n\nconst work = ({ signal }: { signal: AbortSignal }) => Promise.resolve(signal.aborted ? 'cancelled' : 'done')\nconst result = await withTimeout(work, { timeoutMs: 500, report: hostRethrowReporter })\nconsole.log(result) // done：被隔离的异步错误仍交给宿主 reporter 观察", useEn: 'An application has no custom reporter but contained async failures must remain visible.', useZh: 'application 没有 custom reporter，但 contained async failure 仍必须可见。', avoidEn: 'A production telemetry or domain reporter can preserve richer operation context.', avoidZh: 'production telemetry 或 domain reporter 可以保留更丰富 operation context。' }),
  'utils:string:format': utilsGuide({ purposeEn: 'Interpolates safe object paths into a string with explicit delimiter, missing-value, and nullish-value policies.', purposeZh: '把 safe object path 插值到 string 中，并显式控制 delimiter、missing-value 与 nullish-value policy。', quickStart: "import { format } from '@migaia/utils'\n\nconst label = format('Hello {user.name}', { user: { name: 'Ada' } })", useEn: 'Trusted application templates need lightweight named interpolation without executing expressions.', useZh: 'trusted application template 需要轻量 named interpolation，且不能执行 expression。', avoidEn: 'Templates are untrusted HTML, require pluralization, or need a full internationalization message grammar.', avoidZh: 'template 是 untrusted HTML、需要 pluralization，或需要完整 internationalization message grammar。' }),
  'utils:value:isNullish': utilsGuide({ purposeEn: 'Narrows exactly null or undefined without classifying other falsy values as absent.', purposeZh: '只窄化 null 或 undefined，不把其他 falsy value 归类为 absent。', quickStart: "import { isNullish } from '@migaia/utils'\n\nconst value: string | undefined = undefined\nif (isNullish(value)) console.log('use fallback')\nconsole.log(isNullish(0), isNullish(false)) // false false：其他 falsy value 仍保留", useEn: 'Zero, false, empty text, and NaN remain meaningful values.', useZh: 'zero、false、empty text 与 NaN 仍是有意义 value。', avoidEn: 'The domain has a broader explicit emptiness policy.', avoidZh: 'domain 拥有更宽的显式 emptiness policy。' }),
  'utils:value:isBlankString': utilsGuide({ purposeEn: 'Narrows strings whose trimmed content is empty while rejecting all non-string values.', purposeZh: '窄化 trim 后为空的 string，同时拒绝所有 non-string value。', quickStart: "import { isBlankString } from '@migaia/utils'\n\nconst input = '   '\nif (isBlankString(input)) console.warn('required field is blank')", useEn: 'A text field treats whitespace-only input as blank.', useZh: 'text field 把 whitespace-only input 视为 blank。', avoidEn: 'Whitespace is meaningful or non-string absence should also count as blank.', avoidZh: 'whitespace 有意义，或 non-string absence 也应算 blank。' }),
  'utils:value:isEmptyValue': utilsGuide({ purposeEn: 'Applies the shared empty-value policy for null, undefined, blank strings, and NaN while deliberately preserving zero, false, and bigint zero.', purposeZh: '应用 shared empty-value policy：null、undefined、blank string 与 NaN 为空，同时刻意保留 zero、false 与 bigint zero。', quickStart: "import { isEmptyValue } from '@migaia/utils'\n\nconsole.log(isEmptyValue('  '), isEmptyValue(undefined)) // true true\nconsole.log(isEmptyValue(0), isEmptyValue(false)) // false false：zero 和 false 不是缺失", useEn: 'Forms or configuration admission share this exact absence policy.', useZh: 'form 或 configuration admission 共享这一精确 absence policy.', avoidEn: 'The domain defines empty arrays, records, zero, or false as empty.', avoidZh: 'domain 把 empty array、record、zero 或 false 定义为空。' }),
  'utils:value:isPrimitive': utilsGuide({ purposeEn: 'Narrows JavaScript primitive values, including symbol and bigint, while excluding objects and functions.', purposeZh: '窄化 JavaScript primitive value，包括 symbol 与 bigint，同时排除 object 与 function。', quickStart: "import { isPrimitive } from '@migaia/utils'\n\nconst value: unknown = 42\nif (isPrimitive(value)) console.log(value) // scalar 通过 guard 后可按 primitive 处理", useEn: 'A codec, snapshot, or branch handles scalar identity separately from object graphs.', useZh: 'codec、snapshot 或 branch 需要把 scalar identity 与 object graph 分开处理。', avoidEn: 'Only JSON scalar values are accepted, because symbol, bigint, and undefined require separate policy.', avoidZh: '只接受 JSON scalar value；symbol、bigint 与 undefined 需要独立 policy。' })
}

export const utilsApiGuides = {
  ...foundationalUtilsApiGuides,
  ...dataUtilsApiGuides,
  ...controlUtilsApiGuides
} as const
