/** A3: every retained renamed type exists under its new name and rejects its old name. */
export type { IRpcCoreConfig as ILayeringNew001 } from '../../src/core/composed.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcCoreConfig as ILayeringOld001 } from '../../src/core/composed.js'
export type { IRpcKernelSurface as ILayeringNew002 } from '../../src/core/composed.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcKernelSurface as ILayeringOld002 } from '../../src/core/composed.js'
export type { IRpcRootProjection as ILayeringNew003 } from '../../src/core/composed.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcRootProjection as ILayeringOld003 } from '../../src/core/composed.js'
export type { IRpcCoreErrorCode as ILayeringNew004 } from '../../src/core/error-code.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcErrorCode as ILayeringOld004 } from '../../src/core/error-code.js'
export type { IRpcCleanupError as ILayeringNew005 } from '../../src/core/errors.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcCleanupError as ILayeringOld005 } from '../../src/core/errors.js'
export type { IRpcError as ILayeringNew006 } from '../../src/core/errors.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcError as ILayeringOld006 } from '../../src/core/errors.js'
export type { IRpcCoreErrorCode as ILayeringNew007 } from '../../src/core/errors.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcErrorCode as ILayeringOld007 } from '../../src/core/errors.js'
export type { IRpcFeature as ILayeringNew008 } from '../../src/core/feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeature as ILayeringOld008 } from '../../src/core/feature.js'
export type { IRpcFeatureDefinition as ILayeringNew009 } from '../../src/core/feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeatureDefinition as ILayeringOld009 } from '../../src/core/feature.js'
export type { IRpcFeatureSurface as ILayeringNew010 } from '../../src/core/feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeatureSurface as ILayeringOld010 } from '../../src/core/feature.js'
export type { IRpcFiniteFeatureTuple as ILayeringNew011 } from '../../src/core/feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFiniteFeatureTuple as ILayeringOld011 } from '../../src/core/feature.js'
export type { IRpcOneWayOptions as ILayeringNew012 } from '../../src/core/features/one-way.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOneWayOptions as ILayeringOld012 } from '../../src/core/features/one-way.js'
export type { IRpcCleanupError as ILayeringNew013 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcCleanupError as ILayeringOld013 } from '../../src/core/index.js'
export type { IRpcError as ILayeringNew014 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcError as ILayeringOld014 } from '../../src/core/index.js'
export type { IRpcCoreErrorCode as ILayeringNew015 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcErrorCode as ILayeringOld015 } from '../../src/core/index.js'
export type { IRpcFeature as ILayeringNew016 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeature as ILayeringOld016 } from '../../src/core/index.js'
export type { IRpcFeatureDefinition as ILayeringNew017 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeatureDefinition as ILayeringOld017 } from '../../src/core/index.js'
export type { IRpcFeatureSurface as ILayeringNew018 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeatureSurface as ILayeringOld018 } from '../../src/core/index.js'
export type { IRpcMiddlewareCore as ILayeringNew019 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareCore as ILayeringOld019 } from '../../src/core/index.js'
export type { IRpcMiddlewareDescriptor as ILayeringNew020 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareDescriptor as ILayeringOld020 } from '../../src/core/index.js'
export type { IRpcNativeMiddleware as ILayeringNew021 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativeMiddleware as ILayeringOld021 } from '../../src/core/index.js'
export type { IRpcSendOptions as ILayeringNew022 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSendOptions as ILayeringOld022 } from '../../src/core/index.js'
export type { IRpcTransport as ILayeringNew023 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransport as ILayeringOld023 } from '../../src/core/index.js'
export type { IRpcTransportTopology as ILayeringNew024 } from '../../src/core/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportTopology as ILayeringOld024 } from '../../src/core/index.js'
export type { IRpcConstructionControl as ILayeringNew025 } from '../../src/core/internal/construction-install.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConstructionControl as ILayeringOld025 } from '../../src/core/internal/construction-install.js'
export type { IRpcConstructionInstallOptions as ILayeringNew026 } from '../../src/core/internal/construction-install.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConstructionInstallOptions as ILayeringOld026 } from '../../src/core/internal/construction-install.js'
export type { IRpcConstructionTime as ILayeringNew027 } from '../../src/core/internal/construction-install.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConstructionTime as ILayeringOld027 } from '../../src/core/internal/construction-install.js'
export type { IRpcControlPorts as ILayeringNew028 } from '../../src/core/internal/control-attachment.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcControlPorts as ILayeringOld028 } from '../../src/core/internal/control-attachment.js'
export type { IRpcEndpointOptions as ILayeringNew029 } from '../../src/core/internal/endpoint-options.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEndpointOptions as ILayeringOld029 } from '../../src/core/internal/endpoint-options.js'
export type { IRpcSelectedComponents as ILayeringNew030 } from '../../src/core/internal/endpoint-options.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSelectedComponents as ILayeringOld030 } from '../../src/core/internal/endpoint-options.js'
export type { IRpcOutboundCommandObservation as ILayeringNew031 } from '../../src/core/internal/feature-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundCommandObservation as ILayeringOld031 } from '../../src/core/internal/feature-contract.js'
export type { IRpcClaimAdmission as ILayeringNew032 } from '../../src/core/internal/feature-policy.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcClaimAdmission as ILayeringOld032 } from '../../src/core/internal/feature-policy.js'
export type { IRpcFeaturePolicy as ILayeringNew033 } from '../../src/core/internal/feature-policy.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeaturePolicy as ILayeringOld033 } from '../../src/core/internal/feature-policy.js'
export type { IRpcNativeRoleClaimSource as ILayeringNew034 } from '../../src/core/internal/feature-policy.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativeRoleClaimSource as ILayeringOld034 } from '../../src/core/internal/feature-policy.js'
export type { IRpcFirstPartyRootName as ILayeringNew035 } from '../../src/core/internal/first-party-roots.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFirstPartyRootName as ILayeringOld035 } from '../../src/core/internal/first-party-roots.js'
export type { IRpcFirstPartyRoots as ILayeringNew036 } from '../../src/core/internal/first-party-roots.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFirstPartyRoots as ILayeringOld036 } from '../../src/core/internal/first-party-roots.js'
export type { IRpcPublicFirstPartyRootNames as ILayeringNew037 } from '../../src/core/internal/first-party-roots.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPublicFirstPartyRootNames as ILayeringOld037 } from '../../src/core/internal/first-party-roots.js'
export type { IRpcHookFailureReporter as ILayeringNew038 } from '../../src/core/internal/hooks.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcHookFailureReporter as ILayeringOld038 } from '../../src/core/internal/hooks.js'
export type { IRpcOutboundTransport as ILayeringNew039 } from '../../src/core/internal/outbound-sender.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundTransport as ILayeringOld039 } from '../../src/core/internal/outbound-sender.js'
export type { IRpcControlRole as ILayeringNew040 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcControlRole as ILayeringOld040 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcControlRoleContract as ILayeringNew041 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcControlRoleContract as ILayeringOld041 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcFirstPartyRole as ILayeringNew042 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFirstPartyRole as ILayeringOld042 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcFirstPartyRoleContract as ILayeringNew043 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFirstPartyRoleContract as ILayeringOld043 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcPluginConstraint as ILayeringNew044 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginConstraint as ILayeringOld044 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcPluginCore as ILayeringNew045 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginCore as ILayeringOld045 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcPluginHostCore as ILayeringNew046 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginHostCore as ILayeringOld046 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcPluginInstallScope as ILayeringNew047 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginInstallScope as ILayeringOld047 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcProviderCancellationPortMetadata as ILayeringNew048 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderCancellationPortMetadata as ILayeringOld048 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcProviderRole as ILayeringNew049 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderRole as ILayeringOld049 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcProviderRoleContract as ILayeringNew050 } from '../../src/core/internal/plugin-contract.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderRoleContract as ILayeringOld050 } from '../../src/core/internal/plugin-contract.js'
export type { IRpcPluginDescriptor as ILayeringNew051 } from '../../src/core/internal/plugin-descriptor.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginDescriptor as ILayeringOld051 } from '../../src/core/internal/plugin-descriptor.js'
export type { IRpcComposedRuntimeState as ILayeringNew052 } from '../../src/core/internal/plugin-inventory.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcComposedRuntimeState as ILayeringOld052 } from '../../src/core/internal/plugin-inventory.js'
export type { IRpcNativeFeatureDefinition as ILayeringNew053 } from '../../src/core/internal/plugin-inventory.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativeFeatureDefinition as ILayeringOld053 } from '../../src/core/internal/plugin-inventory.js'
export type { IRpcNativePluginBatchEntry as ILayeringNew054 } from '../../src/core/internal/plugin-inventory.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativePluginBatchEntry as ILayeringOld054 } from '../../src/core/internal/plugin-inventory.js'
export type { IRpcNativePluginBatchOptions as ILayeringNew055 } from '../../src/core/internal/plugin-inventory.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativePluginBatchOptions as ILayeringOld055 } from '../../src/core/internal/plugin-inventory.js'
export type { IRpcPluginRole as ILayeringNew056 } from '../../src/core/internal/plugin-inventory.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginRole as ILayeringOld056 } from '../../src/core/internal/plugin-inventory.js'
export type { IRpcAbortEnablePort as ILayeringNew057 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAbortEnablePort as ILayeringOld057 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcAuthenticationPort as ILayeringNew058 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAuthenticationPort as ILayeringOld058 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcCandidatePingPort as ILayeringNew059 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcCandidatePingPort as ILayeringOld059 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcConnectPort as ILayeringNew060 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectPort as ILayeringOld060 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcContractPort as ILayeringNew061 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcContractPort as ILayeringOld061 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcDiscoveryResolverPort as ILayeringNew062 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcDiscoveryResolverPort as ILayeringOld062 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcEndpointTimer as ILayeringNew063 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEndpointTimer as ILayeringOld063 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcHooksPort as ILayeringNew064 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcHooksPort as ILayeringOld064 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcIdentityCommand as ILayeringNew065 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcIdentityCommand as ILayeringOld065 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcInboundIdentityPort as ILayeringNew066 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcInboundIdentityPort as ILayeringOld066 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcOutboundAttachmentPort as ILayeringNew067 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundAttachmentPort as ILayeringOld067 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcOutboundCommand as ILayeringNew068 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundCommand as ILayeringOld068 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcOutboundOperationsPort as ILayeringNew069 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundOperationsPort as ILayeringOld069 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcOutboundSend as ILayeringNew070 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOutboundSend as ILayeringOld070 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcPingEnablePort as ILayeringNew071 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPingEnablePort as ILayeringOld071 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcPortName as ILayeringNew072 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPortName as ILayeringOld072 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcPortValues as ILayeringNew073 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPortValues as ILayeringOld073 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcProtocolPort as ILayeringNew074 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProtocolPort as ILayeringOld074 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcProviderCancellationPort as ILayeringNew075 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderCancellationPort as ILayeringOld075 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcResponseOutboundCommand as ILayeringNew076 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcResponseOutboundCommand as ILayeringOld076 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcSynchronousOutboundCommand as ILayeringNew077 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSynchronousOutboundCommand as ILayeringOld077 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcTimeoutPort as ILayeringNew078 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTimeoutPort as ILayeringOld078 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcTimePort as ILayeringNew079 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTimePort as ILayeringOld079 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcUuidPort as ILayeringNew080 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcUuidPort as ILayeringOld080 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcVariationAdmissionRequest as ILayeringNew081 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcVariationAdmissionRequest as ILayeringOld081 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcVariationCoordinatorPort as ILayeringNew082 } from '../../src/core/internal/plugin-shared-keys.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcVariationCoordinatorPort as ILayeringOld082 } from '../../src/core/internal/plugin-shared-keys.js'
export type { IRpcPortFeature as ILayeringNew083 } from '../../src/core/internal/port-feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPortFeature as ILayeringOld083 } from '../../src/core/internal/port-feature.js'
export type { IRpcPortFeatureRuntime as ILayeringNew084 } from '../../src/core/internal/port-feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPortFeatureRuntime as ILayeringOld084 } from '../../src/core/internal/port-feature.js'
export type { IRpcPortFeatureSet as ILayeringNew085 } from '../../src/core/internal/port-feature.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPortFeatureSet as ILayeringOld085 } from '../../src/core/internal/port-feature.js'
export type { IRpcProviderPorts as ILayeringNew086 } from '../../src/core/internal/provider-attachment.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderPorts as ILayeringOld086 } from '../../src/core/internal/provider-attachment.js'
export type { IRpcEnvelopeData as ILayeringNew087 } from '../../src/contract/index.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcRoutingData as ILayeringOld087 } from '../../src/contract/index.js'
export type { IRpcDiscoveryCleanupFaults as ILayeringNew088 } from '../../src/core/internal/test-observer.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcDiscoveryCleanupFaults as ILayeringOld088 } from '../../src/core/internal/test-observer.js'
export type { IRpcEndpointDebugSnapshot as ILayeringNew089 } from '../../src/core/internal/test-observer.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEndpointDebugSnapshot as ILayeringOld089 } from '../../src/core/internal/test-observer.js'
export type { IRpcProviderRegistration as ILayeringNew090 } from '../../src/core/internal/test-observer.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderRegistration as ILayeringOld090 } from '../../src/core/internal/test-observer.js'
export type { IRpcTimePortEvent as ILayeringNew091 } from '../../src/core/internal/test-observer.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTimePortEvent as ILayeringOld091 } from '../../src/core/internal/test-observer.js'
export type { IRpcPipelineValue as ILayeringNew092 } from '../../src/core/internal/web-rpc-plugin-host.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPipelineValue as ILayeringOld092 } from '../../src/core/internal/web-rpc-plugin-host.js'
export type { IRpcPluginHost as ILayeringNew093 } from '../../src/core/internal/web-rpc-plugin-host.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginHost as ILayeringOld093 } from '../../src/core/internal/web-rpc-plugin-host.js'
export type { IRpcMiddlewareComponentContribution as ILayeringNew094 } from '../../src/core/middleware.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareComponentContribution as ILayeringOld094 } from '../../src/core/middleware.js'
export type { IRpcMiddlewareComponentPolicy as ILayeringNew095 } from '../../src/core/middleware.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareComponentPolicy as ILayeringOld095 } from '../../src/core/middleware.js'
export type { IRpcMiddlewareCore as ILayeringNew096 } from '../../src/core/middleware.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareCore as ILayeringOld096 } from '../../src/core/middleware.js'
export type { IRpcMiddlewareDescriptor as ILayeringNew097 } from '../../src/core/middleware.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddlewareDescriptor as ILayeringOld097 } from '../../src/core/middleware.js'
export type { IRpcNativeMiddleware as ILayeringNew098 } from '../../src/core/middleware.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcNativeMiddleware as ILayeringOld098 } from '../../src/core/middleware.js'
export type { IRpcMessageKind as ILayeringNew099 } from '../../src/core/semantic-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMessageKind as ILayeringOld099 } from '../../src/core/semantic-constants.js'
export type { IRpcCandidateStatus as ILayeringNew101 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcCandidateStatus as ILayeringOld101 } from '../../src/core/transport-constants.js'
export type { IRpcOperation as ILayeringNew102 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcOperation as ILayeringOld102 } from '../../src/core/transport-constants.js'
export type { IRpcPlatformValue as ILayeringNew103 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPlatformValue as ILayeringOld103 } from '../../src/core/transport-constants.js'
export type { IRpcTransportEncodingValue as ILayeringNew104 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportEncodingValue as ILayeringOld104 } from '../../src/core/transport-constants.js'
export type { IRpcTransportOwnershipValue as ILayeringNew105 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportOwnershipValue as ILayeringOld105 } from '../../src/core/transport-constants.js'
export type { IRpcTransportTopologyValue as ILayeringNew106 } from '../../src/core/transport-constants.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportTopologyValue as ILayeringOld106 } from '../../src/core/transport-constants.js'
export type { IRpcInboundMessage as ILayeringNew107 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcInboundMessage as ILayeringOld107 } from '../../src/core/transport.js'
export type { IRpcSendOptions as ILayeringNew108 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSendOptions as ILayeringOld108 } from '../../src/core/transport.js'
export type { IRpcTransport as ILayeringNew109 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransport as ILayeringOld109 } from '../../src/core/transport.js'
export type { IRpcTransportEncoding as ILayeringNew110 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportEncoding as ILayeringOld110 } from '../../src/core/transport.js'
export type { IRpcTransportOwnership as ILayeringNew111 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportOwnership as ILayeringOld111 } from '../../src/core/transport.js'
export type { IRpcTransportTopology as ILayeringNew112 } from '../../src/core/transport.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTransportTopology as ILayeringOld112 } from '../../src/core/transport.js'
export type { IRpcAbortCapability as ILayeringNew113 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAbortCapability as ILayeringOld113 } from '../../src/core/typing.js'
export type { IRpcAbortSignal as ILayeringNew114 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAbortSignal as ILayeringOld114 } from '../../src/core/typing.js'
export type { IRpcAuthenticationCapability as ILayeringNew115 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAuthenticationCapability as ILayeringOld115 } from '../../src/core/typing.js'
export type { IRpcAuthenticationConfig as ILayeringNew116 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAuthenticationConfig as ILayeringOld116 } from '../../src/core/typing.js'
export type { IRpcAuthenticationContext as ILayeringNew117 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAuthenticationContext as ILayeringOld117 } from '../../src/core/typing.js'
export type { IRpcAuthenticationTransform as ILayeringNew118 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAuthenticationTransform as ILayeringOld118 } from '../../src/core/typing.js'
export type { IRpcAutomaticConnectControl as ILayeringNew119 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcAutomaticConnectControl as ILayeringOld119 } from '../../src/core/typing.js'
export type { IRpcConnectCapability as ILayeringNew120 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectCapability as ILayeringOld120 } from '../../src/core/typing.js'
export type { IRpcConnectConfig as ILayeringNew121 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectConfig as ILayeringOld121 } from '../../src/core/typing.js'
export type { IRpcConnectContext as ILayeringNew122 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectContext as ILayeringOld122 } from '../../src/core/typing.js'
export type { IRpcConnectControl as ILayeringNew123 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectControl as ILayeringOld123 } from '../../src/core/typing.js'
export type { IRpcConnectControlForMode as ILayeringNew124 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcConnectControlForMode as ILayeringOld124 } from '../../src/core/typing.js'
export type { IRpcContext as ILayeringNew125 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcContext as ILayeringOld125 } from '../../src/core/typing.js'
export type { IRpcContractCapability as ILayeringNew126 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcContractCapability as ILayeringOld126 } from '../../src/core/typing.js'
export type { IRpcContractConfig as ILayeringNew127 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcContractConfig as ILayeringOld127 } from '../../src/core/typing.js'
export type { IRpcDiscoveryCandidate as ILayeringNew128 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcDiscoveryCandidate as ILayeringOld128 } from '../../src/core/typing.js'
export type { IRpcDiscoveryControl as ILayeringNew129 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcDiscoveryControl as ILayeringOld129 } from '../../src/core/typing.js'
export type { IRpcDiscoveryMode as ILayeringNew130 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcDiscoveryMode as ILayeringOld130 } from '../../src/core/typing.js'
export type { IRpcEndpoint as ILayeringNew131 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEndpoint as ILayeringOld131 } from '../../src/core/typing.js'
export type { IRpcEndpointFactory as ILayeringNew132 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEndpointFactory as ILayeringOld132 } from '../../src/core/typing.js'
export type { IRpcEventListener as ILayeringNew133 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcEventListener as ILayeringOld133 } from '../../src/core/typing.js'
export type { IRpcFactoryConfig as ILayeringNew134 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFactoryConfig as ILayeringOld134 } from '../../src/core/typing.js'
export type { IRpcFanoutResult as ILayeringNew135 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFanoutResult as ILayeringOld135 } from '../../src/core/typing.js'
export type { IRpcFeatureConfig as ILayeringNew136 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcFeatureConfig as ILayeringOld136 } from '../../src/core/typing.js'
export type { IRpcHook as ILayeringNew137 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcHook as ILayeringOld137 } from '../../src/core/typing.js'
export type { IRpcHookEvent as ILayeringNew138 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcHookEvent as ILayeringOld138 } from '../../src/core/typing.js'
export type { IRpcHooksConfig as ILayeringNew139 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcHooksConfig as ILayeringOld139 } from '../../src/core/typing.js'
export type { IRpcInboundDiscoveryQuery as ILayeringNew140 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcInboundDiscoveryQuery as ILayeringOld140 } from '../../src/core/typing.js'
export type { IRpcManualConnectControl as ILayeringNew141 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcManualConnectControl as ILayeringOld141 } from '../../src/core/typing.js'
export type { IRpcMethodSchema as ILayeringNew142 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMethodSchema as ILayeringOld142 } from '../../src/core/typing.js'
export type { IRpcMiddleware as ILayeringNew143 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcMiddleware as ILayeringOld143 } from '../../src/core/typing.js'
export type { IRpcPingCapability as ILayeringNew144 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPingCapability as ILayeringOld144 } from '../../src/core/typing.js'
export type { IRpcPingEndpointSurface as ILayeringNew145 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPingEndpointSurface as ILayeringOld145 } from '../../src/core/typing.js'
export type { IRpcPingOptions as ILayeringNew146 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPingOptions as ILayeringOld146 } from '../../src/core/typing.js'
export type { IRpcPlatform as ILayeringNew147 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPlatform as ILayeringOld147 } from '../../src/core/typing.js'
export type { IRpcPlugin as ILayeringNew148 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPlugin as ILayeringOld148 } from '../../src/core/typing.js'
export type { IRpcPluginClaims as ILayeringNew149 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginClaims as ILayeringOld149 } from '../../src/core/typing.js'
export type { IRpcPluginInstallResult as ILayeringNew150 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginInstallResult as ILayeringOld150 } from '../../src/core/typing.js'
export type { IRpcPluginInstallScope as ILayeringNew151 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginInstallScope as ILayeringOld151 } from '../../src/core/typing.js'
export type { IRpcPluginMetadata as ILayeringNew152 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPluginMetadata as ILayeringOld152 } from '../../src/core/typing.js'
export type { IRpcProtocolCapability as ILayeringNew153 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProtocolCapability as ILayeringOld153 } from '../../src/core/typing.js'
export type { IRpcProtocolConfig as ILayeringNew154 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProtocolConfig as ILayeringOld154 } from '../../src/core/typing.js'
export type { IRpcProvider as ILayeringNew155 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProvider as ILayeringOld155 } from '../../src/core/typing.js'
export type { IRpcProviderLimits as ILayeringNew156 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderLimits as ILayeringOld156 } from '../../src/core/typing.js'
export type { IRpcProviderResult as ILayeringNew157 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcProviderResult as ILayeringOld157 } from '../../src/core/typing.js'
export type { IRpcPublicError as ILayeringNew158 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcPublicError as ILayeringOld158 } from '../../src/core/typing.js'
export type { IRpcSchema as ILayeringNew159 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSchema as ILayeringOld159 } from '../../src/core/typing.js'
export type { IRpcSchemaIssue as ILayeringNew160 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcSchemaIssue as ILayeringOld160 } from '../../src/core/typing.js'
export type { IRpcServerMetadata as ILayeringNew161 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcServerMetadata as ILayeringOld161 } from '../../src/core/typing.js'
export type { IRpcTimeoutCapability as ILayeringNew162 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTimeoutCapability as ILayeringOld162 } from '../../src/core/typing.js'
export type { IRpcTimeoutConfig as ILayeringNew163 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcTimeoutConfig as ILayeringOld163 } from '../../src/core/typing.js'
export type { IRpcUniqueTargetIdContext as ILayeringNew164 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcUniqueTargetIdContext as ILayeringOld164 } from '../../src/core/typing.js'
export type { IRpcUuidConfig as ILayeringNew165 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcUuidConfig as ILayeringOld165 } from '../../src/core/typing.js'
export type { IRpcUuidContext as ILayeringNew166 } from '../../src/core/typing.js'
// @ts-expect-error BC2 removes the old public type name.
export type { IWebRpcUuidContext as ILayeringOld166 } from '../../src/core/typing.js'
