import { identityCodecV1 } from '@migaia/serialize/codec'
import { systemScheduler, type IScheduler } from '@migaia/utils/scheduler'
import { hostRethrowReporter } from '@migaia/utils/promise'
import { createMemoryTransportPair } from '../core/adapters/memory.js'
import { messageFramerV1 } from '../contract/framing/index.js'
import { registerBatchAgreement } from '../core/internal/batch-frame.js'
import { defaultRpcId } from '../core/internal/id.js'
import { RpcCoreErrorCode, RpcError } from '../core/errors.js'
import { IpcReporterContext } from '../core/plugins/reporter-context.js'
import {
  createRuntimePeer,
  prepareRuntimePeerSourceContext,
  type IRuntimePeerOptions,
  type IRuntimePeerProvide,
  type IRuntimePeerSource
} from '../remote/runtime-api/peer.js'
import type { IRuntimeTypedPeer } from '../remote/runtime-api/typing.js'
import { PeerPairName, PeerPairErrorText } from './text.js'

/** Each testing side configures only the same canonical method/deadline/admission owners. */
type IPeerPairSide<P extends IRuntimePeerProvide> = Pick<
  IRuntimePeerOptions,
  'defaultTimeoutMs' | 'providerLimits' | 'contract'
> &
  Readonly<{ provide: P }>

/** Testing configuration never selects a fake endpoint, scheduler implementation or native proof. */
export type IPeerPairOptions<
  A extends IRuntimePeerProvide,
  B extends IRuntimePeerProvide
> = Readonly<{
  a: IPeerPairSide<A>
  b: IPeerPairSide<B>
  scheduler?: IScheduler
  report?: (error: unknown) => void
}>

/** Both handles expose the other side's application types; generic metadata is erased at runtime. */
export function createPeerPair<A extends IRuntimePeerProvide, B extends IRuntimePeerProvide>(
  options: IPeerPairOptions<A, B>
): Promise<Readonly<{ a: IRuntimeTypedPeer<B>; b: IRuntimeTypedPeer<A> }>>

/**
 * Assemble two original Peers over the original reference memory carrier. Portable binary uses
 * canonical inline restoration; explicit transfer is unsupported and fails before detach. The
 * original pair owns close, while each Peer owns its endpoint and rollback scope.
 */
export async function createPeerPair(
  options: IPeerPairOptions<IRuntimePeerProvide, IRuntimePeerProvide>
): Promise<object> {
  /** Both caller-owned side configurations are read before any physical or asynchronous owner. */
  const sides = [options?.a, options?.b] as const
  if (!sides[0] || !sides[1])
    throw new RpcError(RpcCoreErrorCode.invalidConfig, PeerPairErrorText.sidesInvalid)
  /** A second-side getter failure cannot strand a first Peer or replace its primary exception. */
  const configurations = [{ ...sides[0] }, { ...sides[1] }] as const
  /** Same-process source identities are generated by the existing canonical identity owner. */
  const identities = [
    { name: PeerPairName.a, instanceId: defaultRpcId() },
    { name: PeerPairName.b, instanceId: defaultRpcId() }
  ] as const
  /** These are two actual configured canonical assemblies, not one remote offer echo. */
  const offers = identities.map((self) => prepareRuntimePeerSourceContext(self))
  /** The existing scheduler port owns all endpoint deadlines; no testing clock is introduced. */
  const scheduler = options.scheduler ?? systemScheduler
  /** The existing memory owner is the only physical pair and retains its honest carrier metadata. */
  const transports = createMemoryTransportPair()
  /**
   * Reporter failures use the same canonical policy and cannot replace construction's primary
   * error.
   */
  const report = (error: unknown): void => {
    try {
      if (options.report) options.report(error)
      else console.error(error)
    } catch (failure) {
      hostRethrowReporter(failure, IpcReporterContext)
    }
  }
  /** Each source intersects its own compiled offer with the other configured endpoint's offer. */
  const source =
    (index: 0 | 1): IRuntimePeerSource =>
    async (context) => {
      const capabilities = context.capabilities.filter((value) =>
        offers[1 - index]!.capabilities.includes(value)
      )
      registerBatchAgreement(transports[index], capabilities)
      return {
        transport: transports[index],
        peerId: identities[1 - index]!.instanceId,
        scheduler,
        agreement: { source: 'static', codec: identityCodecV1.id, capabilities },
        pipeline: { codec: identityCodecV1, framer: messageFramerV1 },
        features: [],
        close: async () => {
          transports[index].close()
        }
      }
    }
  /** Original Peers compile/validate their own sides and acquire/dispose only their own endpoint. */
  const preparing = [
    createRuntimePeer({ ...configurations[0], self: identities[0], connect: source(0), report }),
    createRuntimePeer({ ...configurations[1], self: identities[1], connect: source(1), report })
  ] as const
  try {
    const [a, b] = await Promise.all(preparing)
    return Object.freeze({ a, b })
  } catch (primary) {
    /** Closing the original pair wakes its actual pending operations before joining construction. */
    try {
      transports[0].close()
    } catch (cleanup) {
      report(cleanup)
    }
    const settled = await Promise.allSettled(preparing)
    for (const result of settled.toReversed()) {
      if (result.status !== 'fulfilled') continue
      try {
        await result.value.close()
      } catch (cleanup) {
        report(cleanup)
      }
    }
    throw primary
  }
}
